#!/bin/bash
#
# +-------------------------------------------------------------------+
# | Very simple script to backup users' '~/bak' directory to          |
# | /var/backups. The directory is compressed into a .tar.gz format,  |
# | and saved to '/var/backups/' as 'home-$user.tar.gz'.              |
# |                                                                   |
# | Each argument is a user, whose bak directory is to be backed up   |
# +-------------------------------------------------------------------+
#
# xeom(root) | 2014-10-08
# xeom(root) | 2014-11-06
#
# Note: this file is executed every morning as root - It thus must only
#  be modifiable by root, or anyone will be able to run anything as
#  root.

cd /home/

for user in $*; do
	tar -zcf /var/backups/home-${user}.tar.gz ${user} --exclude-from="${user}/.bakignore"
done
