#!/bin/bash
#
# +-------------------------------------------------------------------+
# | Very simple script to backup a user's directory to /var/backups.  |
# | Files or directories prefixed with a '.' are pruned, and the      |
# | remainder is compressed into a .tar.gz format, and saved to       |
# | '/var/backups/' as 'home-$user.tar.gz'. The sole argument is the  |
# | of the user whose home directory is tobe backed up.               |
# +-------------------------------------------------------------------+
#
# xeom(root) | 2014-10-08
# xeom(root) | 2014-11-06
#
# Note: this file is executed every morning as root - It thus must only
#  be modifiable by root, or anyone will be able to run anything as
#  root.

for user in $*; do
	tar -zcf /var/backups/home-${user}.tar.gz /home/${user} --exclude=".*" &> /dev/null
done
