#!/bin/bash
#
# +-------------------------------------------------------------------+
# | Very simple script to backup users' '~/bak' directory to          |
# | /var/backups. The directory is compressed into a .tar.gz format,  |
# | and saved to '/var/backups/' as 'home-$user.tar.gz'.              |
# |                                                                   |
# | Each argument is a user, whose bak directory is to be backed up   |
# +-------------------------------------------------------------------+
#

cd /home/

for user in $*; do
	tar -zcf /var/backups/home-${user}.tar.gz ${user} --exclude-from="${user}/.bakignore"
done
