#!/bin/bash
#
# TODO: Explain this thing
#
#
#

batstatus=$(acpi --battery)
temstatus=$(acpi --thermal)

batpercent=$(grep -oP -- "[0-9]+(?=%)" <<< "$batstatus")
temdegrees=$(grep -oP -- "-?[0-9]+(?=\.[0-9]+ degrees)" <<< "$temstatus")

if [[ $(grep "Charging" <<< "$batstatus") ]]; then
	bat="⮎ ($batpercent%)"

elif [[ $(grep "Full" <<< "$batstatus") ]]; then
	bat="⮒"

elif [[ $(grep "Discharging" <<< "$batstatus") ]]; then
	if (( $batpercent > 60 )); then
		bat="⮏ ($batpercent%)"

	elif (( $batpercent > 20 )); then
		bat="⮑ ($batpercent%)"

	else
		bat="⮐ ($batpercent%)"

	fi

else
	bat="?"

fi

echo "$temdegrees°C $bat"
