#!/bin/bash

BATSTATUS=$(acpi --battery)
TEMSTATUS=$(acpi --thermal)

BATPERCENT=$(grep -oP -- "[0-9]+(?=%)" <<< "$BATSTATUS")
TEMDEGREES=$(grep -oP -- "-?[0-9]+(?=\.[0-9]+ degrees)" <<< "$TEMSTATUS")

if [[ $(grep "Charging" <<< "$BATSTATUS") ]]; then
	BAT="⮎ ($BATPERCENT%)"

elif [[ $(grep "Full" <<< "$BATSTATUS") ]]; then
	BAT="⮒"

elif [[ $(grep "Discharging" <<< "$BATSTATUS") ]]; then
	if (( $BATPERCENT > 60 )); then
		BAT="⮏ ($BATPERCENT%)"

	elif (( $BATPERCENT > 20 )); then
		BAT="⮑ ($BATPERCENT%)"

	else
		BAT="⮐ ($BATPERCENT%)"

	fi

else
	BAT="?"

fi

echo "$TEMDEGREES°C $BAT"
