#!/bin/bash
#
# +-------------------------------------------------------------------+
# | Simple script to display information on every upower managed      |
# | battery.                                                          |
# |                                                                   |
# | Any arguments are handed directly to each upower -i command.      |
# +-------------------------------------------------------------------+
#
# xeom | 2014-09-25

printpowerinfo()
{
	path=$(cat -)
	echo "Info for battery: $path"
	upower -i $path $*
}

upower -e | grep "battery_" | printpowerinfo $*
