#!/bin/bash
#
# +-------------------------------------------------------------------+
# | A simple script, which just prints out the colour codes 0:30-0:37 |
# | and 1:30-1:37. For making colour palettes, and escape codes.      |
# +-------------------------------------------------------------------+
#
# xeom | 2014-11-09


for b in {0..1}; do
	for i in {30..47}; do
		printf "\e[${b};${i}m${b};${i}m \e[0m";
	done;
done;

printf "\e[0m"

echo
