#!/bin/bash
#
# +-------------------------------------------------------------------+
# | Fairly simple script to count the amount of one-time use          |
# | passwords left. Since each password can only be used once, it is  |
# | important to generate and securely print out new ones.            |
# |                                                                   |
# | Arguments are used as a format for output, with %t, %u, %r and %p |
# | representing total, used, remaining and percentage remaining      |
# | respectively. %% also prints a single %.                          |
# +-------------------------------------------------------------------+
#

otpw="/home/xeom/.otpw"

total=$(cat $otpw | wc -l | awk '{print $1-2}')
used=$(cat $otpw | grep -- - | wc -l)
remaining=$(( $total - $used ))
percent=$(( (100 * $remaining) / $total ))

output=""

if [[ $* == "" ]]; then
	echo "Used: $used"
	echo "Total: $total"
	echo "Remaining: $remaining"

else
	escaped=false

	args=$*

	for argind in $(eval echo {0..${#args}}); do
		arg=${args:$argind:1}

		if [[ $escaped == true ]]; then
			if [[ $arg == "u" ]]; then
				output+="$used"

			elif [[ $arg == "t" ]]; then
				output+="$total"

			elif [[ $arg == "r" ]]; then
				output+="$remaining"

			elif [[ $arg == "p" ]]; then
				output+="$percent"

			else
				output+="$arg"
			fi

			broken=false

		elif [[ $arg == "%" ]]; then
			escaped=true

		else
			output+="$arg"

		fi
	done

	echo "$output"
fi
