#!/bin/bash

BATSTATUS=$(acpi --battery)
BATPERCENT=$(grep -oP "[0-9]+(?=%)" <<< "$BATSTATUS")

LOWTHRESHOLD="15"

if [[ $(grep Discharging <<< "$BATSTATUS") && (( $BATPERCENT -lt $LOWTHRESHOLD )) ]]; then
	notify-send "Battery low" "Battery at $BATPERCENT%" -u critical;
fi
