#!/bin/bash

batstatus=$(acpi --battery)
batpercent=$(grep -oP "[0-9]+(?=%)" <<< "$batstatus")

lowthreshold="15"

if [[ $(grep Discharging <<< "$batstatus") && (( $batpercent -lt $lowthreshold )) ]]; then
	notifyscript -u critical "Battery low: Battery at $batpercent%";
fi
