#!/bin/bash

BATSTATUS=$(acpi --battery)
BATPERCENT=$(grep -oP "[0-9]+(?=%)" <<< "$BATSTATUS")

if [[ $(grep Discharging <<< "$BATSTATUS") && (( $BATPERCENT < 15 )) ]]; then
	i3-nagbar -m "Battery below 15%, wtf you little shit?";
fi
