#!/bin/bash
#
# +-------------------------------------------------------------------+
# | A script that waits for a bell character to be input to stdin. It |
# | then notifies the user via notifyscript. This is best used with   |
# | programs like irc with "| tee >(notifybell programname)".         |
# +-------------------------------------------------------------------+
#

name="<unknown>"

# If there is an argument, use it as program name
[[ $1 ]] && name=$1

tee >(while true; do
# Read, ignoring escapes, until the first bell char if
# no bell is received in 10 seconds, the script loops
	read -r -d $'\a' -t 10
	code=$?

# If the code is a timeout error, continue
	if   [[ $code >  128 ]]; then
		continue

# If read returned eof, suicide
	elif [[ $code !=   0 ]]; then
		exit 0
	fi

# If read returned success, notify user of bell
	notify-send "Bell Alert" $name
done)
