#!/bin/bash
#
# +-------------------------------------------------------------------+
# | A script that waits for a bell character to be input to stdin. It |
# | then notifies the user via notifyscript. This is best used with   |
# | programs like irc with "| tee >(notifybell programname)".         |
# +-------------------------------------------------------------------+
#

# If there is an argument, use it as program name
if [[ $1 ]]; then
	name=$1
else
# default
	name="<unknown>"
fi

code=1

while true; do
# Read, ignoring escapes, until the first bell char if
# no bell is received in 10 seconds, the script loops
	read -r -d "" -t 10;
	code=$?

# If the code is a timeout error, continue
	if [[ $code > 128 ]]; then
		continue
	fi

# If read returned eof, suicide
	if [[ $code != 0 ]]; then
		break;
	fi

# If read returned success, notify user of bell
	notifyscript -t "Bell received" $name
done;
