#!/bin/bash
#
# +-------------------------------------------------------------------+
# | Script that should be keybound to PrtSc (Print), to create and    |
# | sync screenshots automatically.                                   |
# |                                                                   |
# | scrot is used to take the screenshots, and they are saved in      |
# | "~/syn/screenshots" with a time and date stamp, in a .png format  |
# +-------------------------------------------------------------------+
#
# xeom | 2014-11-10

ssdir="/home/${USER}/syn/scr/"
ssformat="%Y-%m-%d_%H-%M-%S.png"

file=${ssdir}$(date +${ssformat})

scrot $file
websync -f

notifyscript -u low Took and uploaded screenshot
