#!/bin/bash
#
# +-------------------------------------------------------------------+
# | Script that should be keybound to PrtSc (Print), to create and    |
# | sync screenshots automatically.                                   |
# |                                                                   |
# | scrot is used to take the screenshots, and they are saved in      |
# | "~/syn/screenshots" with a time and date stamp, in a .png format  |
# +-------------------------------------------------------------------+
#

webdir="img/scr/"
webdom="http://f.xeo.la/"
ssdir="/home/${USER}/syn/"

#file=${ssdir}$(date +${ssformat})
name=$(echo "(.png by default)" | dmenu -p "Name screenshot: ")
if [[ -z $name ]]; then
	exit 0
fi

if [[ ! $name == *.png ]]; then
	name="${name}.png"
fi

file=${ssdir}${webdir}${name}
url=${webdom}${webdir}${name}
scrot ${file}
echo ${file}
websync -f

notify-script -u low Took and uploaded screenshot $name
echo ${url} | xclip -selection clipboard
echo ${url} | xclip -selection primary
