#!/bin/bash
#
# +-------------------------------------------------------------------+
# | Syncs '~/websync' to '~/web/files/$(hostNAME)' on canberra this   |
# | is then accessible at 'http://xeo.la/f/$(hostNAME)/'.             |
# |                                                                   |
# | The script logs the output of the last sync to                    |
# | '~/doc/log/websync.log', and if its timestamp is before that of   |
# | '~/websync', it syncs automatically. The 'f' option will force a  |
# | sync, and not update the log, but rather print it to stdout. The  |
# | 'u' option may be invoked to update the log timestamp and nothing |
# | else.                                                             |
# |                                                                   |
# | Please note: This script is not intended for any kind of general  |
# |              use. Death will result.                              |
# +-------------------------------------------------------------------+
#

flags="-Lazv --delete-after"
host="xeom@xeo.la"
remote="~/srv/python-web/files/files/$HOSTNAME"

log=$HOME/doc/log/websync.log
tosync=$HOME/syn

getmtime()
{
	echo $(stat -c %Y $1)
}

getmtimerecursive()
{
	getmtime $(ls --sort=time $(find $1 -type f))
}

[[ ! -f $log ]] && touch $log

if [[ $* == *u* ]]; then
	touch $log

elif [[ $* == *f* ]]; then
	rsync $flags $tosync/ $host:$remote

elif (( $(getmtime $log) < $(getmtimerecursive $tosync) )); then
	if [[ $* == *v* ]]; then
		rsync $flags $tosync/ $host:$remote
	else
		rsync $flags $tosync/ $host:$remote >> $log
	fi
	notifyscript "Synchronized with server"
fi
